app_id: 2a97c291-1238-4561-b988-df561da2798c
app_secret: M2433WYUMZlf~._SoFxLomPUV4ME.KF-9I
redirect: "http://localhost:8000/callback"
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/iitg.ac.in"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
